name: Make JSDocs
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    #  - name: Wait for test to succeed
    #    uses: fountainhead/action-wait-for-check@v1.2.0
    #    with:
    #      token: ${{ secrets.GITHUB_TOKEN }}
    #      checkName: 'upload-analysis-results-to-github'
          
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Make Docs
        uses: andstor/jsdoc-action@v1
        with:
          source_dir: ./source/assets
          output_dir: .
          recurse: true

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: .
